# SERVER
spring.application.name=dssd-backend
server.port=9090

# DATA SOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/dssd-backend
spring.datasource.username=dssd-backend
spring.datasource.password=dssd-backend

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

external.service.url=${SERVICE_URL:http://localhost:8080}

# API CLOUD
cloud.username=pp.back
cloud.apiKey=pp.back
cloud.baseUrl=${API_CLOUD_URL:https://dssd-api-cloud-5axt.onrender.com}

# Chulian
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.http=DEBUG